routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('home')->get('/', 'SiteController@index');
//Route::name('home')->get('/site', 'SiteController@index');
/* Route::name('construcao')->get('/construcao', 'SiteController@construcao'); */
Route::name('noticias')->get('/site/noticias', 'SiteController@noticias');
Route::name('artigo')->get('/site/noticias/{slug}', 'SiteController@article');

Auth::routes(['register' => false]);

Route::post('contact', 'SiteController@contact')->name('site.contact');

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');
    Route::get('contatos', 'AdminController@contact')->name('contact');

    Route::prefix('inicio')->name('home.')->group(function() {
        Route::get('', 'HomeController@index')->name('index');
        Route::get('create', 'HomeController@create')->name('create');
        Route::post('create', 'HomeController@store')->name('store');
        Route::get('{id}', 'HomeController@show')->name('show');
        Route::post('{id}', 'HomeController@update')->name('update');
        Route::get('{id}/delete', 'HomeController@delete')->name('delete'); 
    });

    Route::prefix('servicos')->name('service.')->group(function() {
        Route::get('', 'ServiceController@index')->name('index');
        Route::get('create', 'ServiceController@create')->name('create');
        Route::post('create', 'ServiceController@store')->name('store');
        Route::get('descricao', 'ServiceController@createDesc')->name('createDesc');
        Route::post('descricao', 'ServiceController@updateDesc')->name('updateDesc');
        Route::get('sobre', 'ServiceController@createAbout')->name('createAbout');
        Route::post('sobre', 'ServiceController@updateAbout')->name('updateAbout');
        Route::get('numeros', 'ServiceController@createNumber')->name('createNumber');
        Route::post('numeros', 'ServiceController@updateNumber')->name('updateNumber');
        Route::get('{id}', 'ServiceController@show')->name('show');
        Route::post('{id}', 'ServiceController@update')->name('update');
        Route::get('{id}/delete', 'ServiceController@delete')->name('delete'); 
    });

    Route::prefix('depoimento')->name('testimonial.')->group(function() {
        Route::get('', 'TestimonyController@index')->name('index');
        Route::get('create', 'TestimonyController@create')->name('create');
        Route::post('create', 'TestimonyController@store')->name('store');
        Route::get('{id}', 'TestimonyController@show')->name('show');
        Route::post('{id}', 'TestimonyController@update')->name('update');
        Route::get('{id}/delete', 'TestimonyController@delete')->name('delete'); 
    });

    Route::prefix('profissionais')->name('team.')->group(function() {
        Route::get('', 'TeamController@index')->name('index');
        Route::get('create', 'TeamController@create')->name('create');
        Route::post('create', 'TeamController@store')->name('store');
        Route::get('descricao', 'TeamController@createDesc')->name('createDesc');
        Route::post('descricao', 'TeamController@updateDesc')->name('updateDesc');
        Route::get('{id}', 'TeamController@show')->name('show');
        Route::post('{id}', 'TeamController@update')->name('update');
        Route::get('{id}/delete', 'TeamController@delete')->name('delete'); 
    });

    Route::prefix('posts/categorias')->name('post.category.')->group(function() {
        Route::get('', 'PostCategoryController@index')->name('index');
        Route::get('create', 'PostCategoryController@create')->name('create');
        Route::post('create', 'PostCategoryController@store')->name('store');
        Route::get('{id}', 'PostCategoryController@show')->name('show');
        Route::post('{id}', 'PostCategoryController@update')->name('update');
        Route::get('{id}/delete', 'PostCategoryController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('', 'PostController@index')->name('index');
        Route::get('create', 'PostController@create')->name('create');
        Route::post('create', 'PostController@store')->name('store');
        Route::get('{id}', 'PostController@show')->name('show');
        Route::post('{id}', 'PostController@update')->name('update');
        Route::get('{id}/delete', 'PostController@delete')->name('delete');
    });
});

app/Models/Post.php
<?php

namespace App\Models;

use App\Scopes\LangScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Post extends Model
{
    use LangScope;

    protected $fillable = [
        'title',
        'subtitle',
        'active',
        'slug',
        'image',
        'read',
        'text',
        'category_id',
        'lang',
        'user_id'
    ];

    protected $dates = ['created_at'];

    public function category()
    {
        return $this->belongsTo(PostCategory::class, 'category_id');
    }

    public function scopeOrderDesc($query)
    {
        return $query->orderBy('id', 'DESC');
    }

    public function scopeOrderRead($query)
    {
        return $query->orderBy('read', 'DESC');
    }

    public function scopeBySlug($query, $slug)
    {
        return $query->where('slug', $slug)->first();
    }

    public function scopeByCat($query, $cat)
    {
        return $query->where('category_id', $cat)->take(3)->get();
    }

    public function getCategoryNameAttribute()
    {
        return $this->category->name;
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\PostCategory;
use Illuminate\Http\Request;

class PostController extends Controller
{
    protected $post;

    public function __construct(Post $p) {
        $this->middleware('auth');
        $this->post = $p;
    }

    public function index(Request $request)
    {
        $query = $request->q ?: '';
        $data = $this->post;
        if ($query) {
            $data = $data->where('title', 'like', "%{$query}%");
        }
        $data = $data->get();

        return view('admin.dashboard.posts.index', compact('data', 'query'));
    }

    public function create()
    {
        $categories = PostCategory::pluck('name', 'id')->toArray();

        return view('admin.dashboard.posts.form', compact('categories'));
    }

    public function store(Request $request)
    {
        $input = $request->all();
        $imageName = time().'.'.$input['image']->extension();  
        $input['image']->move(public_path('storage/posts'), $imageName);

        $input['image'] = $imageName;
        $input['slug'] = \Str::slug($input['title'], '-');
        $input['user_id'] = auth()->user()->id;
        $this->post->create($input);

        return redirect()->route('adm.post.index');
    }

    public function show($id)
    {
        $post = $this->post->find($id);
        $categories = PostCategory::pluck('name', 'id')->toArray();

        return view('admin.dashboard.posts.form', compact('post', 'categories'));
    }

    public function update($id, Request $request)
    {
        $input = $request->all();
        $this->post->find($id)->update($input);

        return redirect()->route('adm.post.index');
    }

    public function delete($id)
    {
        $this->post->find($id)->delete();
        
        return redirect()->route('adm.post.index');
    }
}

resources/views/admin/dashboard/posts/form.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Posts</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> Cadastrar
            </h4>
          </div>
          <div class="card-body row">
            @if(isset($post))
                {!! Form::model($post, ['route' => ['adm.post.update', $post->id], 'files' => true]) !!}
            @else
                {!! Form::open(['route' => 'adm.post.store', 'files' => true]) !!}
            @endif
              Título (50 caracteres): {!! Form::text('title', null, ['class' => 'form-control', 'maxlength' => 50, 'required']) !!}
              <br>
              Sub título: {!! Form::text('subtitle', null, ['class' => 'form-control', 'required']) !!}
              <br>
              Categoria: {!! Form::select('category_id', $categories, null, ['class' => 'form-control', 'required']) !!}
              <br>
              @if(!isset($post))
                Capa: {!! Form::file('image') !!}
                <br>
              @endif
              Lang: {!! Form::select('lang', ['pt' => 'PT', 'en' => 'EN'], null, ['class' => 'form-control', 'required']) !!}
              <br>
              Texto: {!! Form::textarea('text', null, ['class' => 'form-control ckeditor', 'required']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

@endsection

@section('scripts')
  <script src="{{ url('ckeditor/ckeditor.js') }}"></script>
@endsection

resources/views/admin/dashboard/posts/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header d-flex justify-content-between">
    <h1>Posts</h1>
    <a href="{{ route('adm.post.create') }}" class="btn btn-success">Cadastrar</a>
  </div>
  <div class="section-header d-flex justify-content-between">
    <h1>Pesquisar</h1>
    <br>
    <form action="#">
      <div class="box-search">
        <input type="text" name="q" value="{{$query}}" placeholder="Buscar" autofocus>
        <button><i class="fa fa-search" aria-hidden="true"></i></button>
      </div>
    </form>
  </div>
  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <table class="table table-responsive">
            <thead class="thead-light">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Categoria</th>
                <th scope="col">Visualizações</th>
                <th scope="col">Lang</th>
                <th scope="col">Opções</th>
              </tr>
            </thead>
            <tbody>
              @foreach($data as $post)
              <tr>
                <th scope="row">{{$post->id}}</th>
                <td>{{$post->title}}</td>
                <td>{{$post->category_name}}</td>
                <td>{{$post->read}}</td>
                <td>{{$post->lang}}</td>
                <td>
                  <a href="{{ route('adm.post.show', $post->id) }}">Editar</a> | 
                  <a href="{{ route('adm.post.delete', $post->id)}} " onclick="return confirm('Deseja mesmo apagar?')">Apagar</a>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection