routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('home')->get('/', 'SiteController@index');
//Route::name('home')->get('/site', 'SiteController@index');
/* Route::name('construcao')->get('/construcao', 'SiteController@construcao'); */
Route::name('noticias')->get('/site/noticias', 'SiteController@noticias');
Route::name('artigo')->get('/site/noticias/{slug}', 'SiteController@article');

Auth::routes(['register' => false]);

Route::post('contact', 'SiteController@contact')->name('site.contact');

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');
    Route::get('contatos', 'AdminController@contact')->name('contact');

    Route::prefix('inicio')->name('home.')->group(function() {
        Route::get('', 'HomeController@index')->name('index');
        Route::get('create', 'HomeController@create')->name('create');
        Route::post('create', 'HomeController@store')->name('store');
        Route::get('{id}', 'HomeController@show')->name('show');
        Route::post('{id}', 'HomeController@update')->name('update');
        Route::get('{id}/delete', 'HomeController@delete')->name('delete'); 
    });

    Route::prefix('servicos')->name('service.')->group(function() {
        Route::get('', 'ServiceController@index')->name('index');
        Route::get('create', 'ServiceController@create')->name('create');
        Route::post('create', 'ServiceController@store')->name('store');
        Route::get('descricao', 'ServiceController@createDesc')->name('createDesc');
        Route::post('descricao', 'ServiceController@updateDesc')->name('updateDesc');
        Route::get('sobre', 'ServiceController@createAbout')->name('createAbout');
        Route::post('sobre', 'ServiceController@updateAbout')->name('updateAbout');
        Route::get('numeros', 'ServiceController@createNumber')->name('createNumber');
        Route::post('numeros', 'ServiceController@updateNumber')->name('updateNumber');
        Route::get('{id}', 'ServiceController@show')->name('show');
        Route::post('{id}', 'ServiceController@update')->name('update');
        Route::get('{id}/delete', 'ServiceController@delete')->name('delete'); 
    });

    Route::prefix('depoimento')->name('testimonial.')->group(function() {
        Route::get('', 'TestimonyController@index')->name('index');
        Route::get('create', 'TestimonyController@create')->name('create');
        Route::post('create', 'TestimonyController@store')->name('store');
        Route::get('{id}', 'TestimonyController@show')->name('show');
        Route::post('{id}', 'TestimonyController@update')->name('update');
        Route::get('{id}/delete', 'TestimonyController@delete')->name('delete'); 
    });

    Route::prefix('profissionais')->name('team.')->group(function() {
        Route::get('', 'TeamController@index')->name('index');
        Route::get('create', 'TeamController@create')->name('create');
        Route::post('create', 'TeamController@store')->name('store');
        Route::get('descricao', 'TeamController@createDesc')->name('createDesc');
        Route::post('descricao', 'TeamController@updateDesc')->name('updateDesc');
        Route::get('{id}', 'TeamController@show')->name('show');
        Route::post('{id}', 'TeamController@update')->name('update');
        Route::get('{id}/delete', 'TeamController@delete')->name('delete'); 
    });

    Route::prefix('posts/categorias')->name('post.category.')->group(function() {
        Route::get('', 'PostCategoryController@index')->name('index');
        Route::get('create', 'PostCategoryController@create')->name('create');
        Route::post('create', 'PostCategoryController@store')->name('store');
        Route::get('{id}', 'PostCategoryController@show')->name('show');
        Route::post('{id}', 'PostCategoryController@update')->name('update');
        Route::get('{id}/delete', 'PostCategoryController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('', 'PostController@index')->name('index');
        Route::get('create', 'PostController@create')->name('create');
        Route::post('create', 'PostController@store')->name('store');
        Route::get('{id}', 'PostController@show')->name('show');
        Route::post('{id}', 'PostController@update')->name('update');
        Route::get('{id}/delete', 'PostController@delete')->name('delete');
    });
});

app/Models/Team.php
<?php

namespace App\Models;

use App\Scopes\LangScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Team extends Model
{
    use LangScope;
    
    protected $table = 'team';
    
    protected $fillable = [
        'name', 'job', 'image', 'text', 'lang'
    ];
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use App\Models\Team;
use App\Models\TeamDesc;
use Illuminate\Http\Request;

class TeamController extends Controller
{
    protected $team;

    public function __construct(Team $team) {
        $this->middleware('auth');
        $this->team = $team;
    }

    public function index()
    {
        $data = $this->team->all();

        return view('admin.dashboard.team.index', compact('data'));
    }

    public function create()
    {
        return view('admin.dashboard.team.form');
    }

    public function store(Request $request)
    {
        $input = $request->all();
        $imageName = time().'.'.$input['image']->extension();  
        $input['image']->move(public_path('storage/team'), $imageName);

        $input['image'] = $imageName;
        $this->team->create($input);

        return redirect()->route('adm.team.index');
    }

    public function show($id)
    {
        $team = $this->team->find($id);
        $data = $this->team->all();

        return view('admin.dashboard.team.form', compact('team', 'data'));
    }

    public function update($id, Request $request)
    {
        $input = $request->all();
        if ($input['image']) {
            $imageName = time().'.'.$input['image']->extension();  
            $input['image']->move(public_path('storage/team'), $imageName);

            $input['image'] = $imageName;
        } else {
            unset($input['image']);
        }
        $this->team->find($id)->update($input);

        return redirect()->route('adm.team.index');
    }

    public function delete($id)
    {
        $this->team->find($id)->delete();
        
        return redirect()->route('adm.team.index');
    }

    public function createDesc()
    {
        $pt = TeamDesc::find(1);
        $en = TeamDesc::find(2);

        return view('admin.dashboard.team.desc', compact('pt', 'en'));
    }

    public function updateDesc(Request $request)
    {
        $desc = TeamDesc::find(1)->update(['text' => $request->pt]);
        $desc = TeamDesc::find(2)->update(['text' => $request->en]);

        toastr()->success('Salvo');

        return redirect()->route('adm.team.createDesc');
    }
}

resources/views/admin/dashboard/team/desc.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Descrição</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> Título
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.team.updateDesc']) !!}
              PT: {!! Form::textarea('pt', $pt->text, ['class' => 'form-control', 'required']) !!}
              EN: {!! Form::textarea('en', $en->text, ['class' => 'form-control', 'required']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection

resources/views/admin/dashboard/team/form.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Profissionais</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> Cadastrar
            </h4>
          </div>
          <div class="card-body row">
            @if(isset($team))
                {!! Form::model($team, ['route' => ['adm.team.update', $team->id], 'files' => true]) !!}
            @else
                {!! Form::open(['route' => 'adm.team.store', 'files' => true]) !!}
            @endif
              Nome: {!! Form::text('name', null, ['class' => 'form-control', 'required']) !!}
              <br>
              Ocupação: {!! Form::text('job', null, ['class' => 'form-control', 'required']) !!}
              <br>
              Imagem: {!! Form::file('image') !!}
              <br>
              Lang: {!! Form::select('lang', ['pt' => 'PT', 'en' => 'EN'], null, ['class' => 'form-control', 'required']) !!}
              <br>
              Texto: {!! Form::textarea('text', null, ['class' => 'form-control ckeditor', 'required']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

@endsection

@section('scripts')
  <script src="http://vip.ufcode.com.br/ckeditor/ckeditor.js"></script>
@endsection

resources/views/admin/dashboard/team/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header d-flex justify-content-between">
    <h1>Profissionais</h1>
    <a href="{{ route('adm.team.create') }}" class="btn btn-success">Cadastrar</a>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Lang</th>
                <th>Opções</th>
              </tr>
            </thead>
            <tbody>
              @foreach($data as $team)
              <tr>
                <td>{{$team->id}}</th>
                <td>{{$team->name}}</td>
                <td>{{$team->lang}}</td>
                <td>
                  <a href="{{ route('adm.team.show', $team->id) }}">Editar</a> | 
                  <a href="{{ route('adm.team.delete', $team->id)}} " onclick="return confirm('Deseja mesmo apagar?')">Apagar</a>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection