routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('home')->get('/', 'SiteController@index');
//Route::name('home')->get('/site', 'SiteController@index');
/* Route::name('construcao')->get('/construcao', 'SiteController@construcao'); */
Route::name('noticias')->get('/site/noticias', 'SiteController@noticias');
Route::name('artigo')->get('/site/noticias/{slug}', 'SiteController@article');

Auth::routes(['register' => false]);

Route::post('contact', 'SiteController@contact')->name('site.contact');

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');
    Route::get('contatos', 'AdminController@contact')->name('contact');

    Route::prefix('inicio')->name('home.')->group(function() {
        Route::get('', 'HomeController@index')->name('index');
        Route::get('create', 'HomeController@create')->name('create');
        Route::post('create', 'HomeController@store')->name('store');
        Route::get('{id}', 'HomeController@show')->name('show');
        Route::post('{id}', 'HomeController@update')->name('update');
        Route::get('{id}/delete', 'HomeController@delete')->name('delete'); 
    });

    Route::prefix('servicos')->name('service.')->group(function() {
        Route::get('', 'ServiceController@index')->name('index');
        Route::get('create', 'ServiceController@create')->name('create');
        Route::post('create', 'ServiceController@store')->name('store');
        Route::get('descricao', 'ServiceController@createDesc')->name('createDesc');
        Route::post('descricao', 'ServiceController@updateDesc')->name('updateDesc');
        Route::get('sobre', 'ServiceController@createAbout')->name('createAbout');
        Route::post('sobre', 'ServiceController@updateAbout')->name('updateAbout');
        Route::get('numeros', 'ServiceController@createNumber')->name('createNumber');
        Route::post('numeros', 'ServiceController@updateNumber')->name('updateNumber');
        Route::get('{id}', 'ServiceController@show')->name('show');
        Route::post('{id}', 'ServiceController@update')->name('update');
        Route::get('{id}/delete', 'ServiceController@delete')->name('delete'); 
    });

    Route::prefix('depoimento')->name('testimonial.')->group(function() {
        Route::get('', 'TestimonyController@index')->name('index');
        Route::get('create', 'TestimonyController@create')->name('create');
        Route::post('create', 'TestimonyController@store')->name('store');
        Route::get('{id}', 'TestimonyController@show')->name('show');
        Route::post('{id}', 'TestimonyController@update')->name('update');
        Route::get('{id}/delete', 'TestimonyController@delete')->name('delete'); 
    });

    Route::prefix('profissionais')->name('team.')->group(function() {
        Route::get('', 'TeamController@index')->name('index');
        Route::get('create', 'TeamController@create')->name('create');
        Route::post('create', 'TeamController@store')->name('store');
        Route::get('descricao', 'TeamController@createDesc')->name('createDesc');
        Route::post('descricao', 'TeamController@updateDesc')->name('updateDesc');
        Route::get('{id}', 'TeamController@show')->name('show');
        Route::post('{id}', 'TeamController@update')->name('update');
        Route::get('{id}/delete', 'TeamController@delete')->name('delete'); 
    });

    Route::prefix('posts/categorias')->name('post.category.')->group(function() {
        Route::get('', 'PostCategoryController@index')->name('index');
        Route::get('create', 'PostCategoryController@create')->name('create');
        Route::post('create', 'PostCategoryController@store')->name('store');
        Route::get('{id}', 'PostCategoryController@show')->name('show');
        Route::post('{id}', 'PostCategoryController@update')->name('update');
        Route::get('{id}/delete', 'PostCategoryController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('', 'PostController@index')->name('index');
        Route::get('create', 'PostController@create')->name('create');
        Route::post('create', 'PostController@store')->name('store');
        Route::get('{id}', 'PostController@show')->name('show');
        Route::post('{id}', 'PostController@update')->name('update');
        Route::get('{id}/delete', 'PostController@delete')->name('delete');
    });
});

resources/views/admin/partials/breadcrumbs.blade.php
@if(Agent::isDesktop())
@if (count($breadcrumbs))
  <div class="section-header-breadcrumb">
    @foreach ($breadcrumbs as $breadcrumb)
      @if ($breadcrumb->url && !$loop->last)
        <div class="breadcrumb-item">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @else
        <div class="breadcrumb-item breadcrumb-active">
          <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
        </div>
      @endif
    @endforeach
  </div>
@endif
@endif

resources/views/admin/partials/fonticons.blade.php
<link rel="stylesheet" href="{{asset('assets_fronts/icon-fonts/css/style.css')}}">

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
  <div class="footer-left">
    Copyright &copy; {{date('Y')}}
    <div class="bullet"></div> Desenvolvido e mantido por  <a href="https://qualitare.com/">Qualitare</a>
  </div>
  <div class="footer-right">
    1.0.0
  </div>
</footer>

resources/views/admin/partials/nav.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
    </ul>
  </form>
  <ul class="navbar-nav navbar-right">
    @auth()
    <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
      <div class="d-sm-none d-lg-inline-block">Olá, {{ auth()->user()->name }}</div></a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-divider"></div>
        {!! Form::open(['route' => 'logout']) !!}
        <button type="submit">
          <i class="fas fa-sign-out-alt"></i> Logout
        <button>
        </form>
      </div>
    </li>
    @endauth
  </ul>
</nav>

resources/views/admin/partials/placeable.blade.php
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4>Endereço</h4>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-12 col-md-3">
            <div class="form-group mb-4">
              {!! Form::hidden('address[id]', isset($result->placeable) ? $result->placeable->id : null) !!}
              {!! Form::label('address[cep]', 'CEP', ['class' => '']) !!}
              {!! Form::text('address[cep]', isset($result->placeable) ? $result->placeable->cep : old('address[cep]'), ['class' => 'form-control js-mask-cep', 'id' => 'cep']) !!}
              @if($errors->has('address.cep'))
                <span class="text-danger">{{ $errors->first('address.cep') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-9">
            <div class="form-group mb-4">
              {!! Form::label('address[street]', 'Rua', ['class' => '']) !!}
              {!! Form::text('address[street]', isset($result->placeable) ? $result->placeable->street : old('address[street]'), ['class' => 'form-control', 'id' => 'rua']) !!}
              @if($errors->has('address.street'))
                <span class="text-danger">{{ $errors->first('address.street') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-5">
            <div class="form-group mb-4">
              {!! Form::label('address[neighborhood]', 'Bairro', ['class' => '']) !!}
              {!! Form::text('address[neighborhood]', isset($result->placeable) ? $result->placeable->neighborhood : old('address[neighborhood]'), ['class' => 'form-control', 'id' => 'bairro']) !!}
              @if($errors->has('address.neighborhood'))
                <span class="text-danger">{{ $errors->first('address.neighborhood') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-5">
            <div class="form-group mb-4">
              {!! Form::label('address[complement]', 'Complemento', ['class' => '']) !!}
              {!! Form::text('address[complement]', isset($result->placeable) ? $result->placeable->complement : old('address[complement]'), ['class' => 'form-control']) !!}
              @if($errors->has('address.complement'))
                <span class="text-danger">{{ $errors->first('address.complement') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-2">
            <div class="form-group mb-4">
              {!! Form::label('address[number]', 'Número', ['class' => '']) !!}
              {!! Form::text('address[number]', isset($result->placeable) ? $result->placeable->number : old('address[number]'), ['class' => 'form-control']) !!}
              @if($errors->has('address.number'))
                <span class="text-danger">{{ $errors->first('address.number') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-3">
            <div class="form-group mb-4">
              {!! Form::label('address[city]', 'Cidade', ['class' => '']) !!}
              {!! Form::text('address[city]', isset($result->placeable) ? $result->placeable->city : old('address[city]'), ['class' => 'form-control', 'id' => 'localidade']) !!}
              @if($errors->has('address.city'))
                <span class="text-danger">{{ $errors->first('address.city') }}</span>
              @endif
            </div>
          </div>
          <div class="col-sm-12 col-md-2">
            <div class="form-group mb-4">
              {!! Form::label('address[state]', 'Estado', ['class' => '']) !!}
              {!! Form::text('address[state]', isset($result->placeable) ? $result->placeable->state : old('address[state]'), ['class' => 'form-control', 'id' => 'uf']) !!}
              @if($errors->has('address.state'))
                <span class="text-danger">{{ $errors->first('address.state') }}</span>
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/partials/scripts.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js"></script>

<script src="{{ asset('/assets/js/mask.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/pt.js"></script>


<script src="{{ asset('/assets/js/stisla.js') }}"></script>
<!-- JS Libraies -->

<!-- Template JS File -->
<script src="{{ asset('/assets/js-duallistbox/jquery.bootstrap-duallistbox.js') }}"></script>
<script src="{{ asset('/assets/js/scripts.js') }}"></script>
<script src="{{ asset('/assets/js/custom.js') }}"></script>
<script src="{{ asset('/assets/js/cep.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.26.14/sweetalert2.all.min.js"></script>
<script src="{{ asset('/assets/js/admin.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.js"></script>
<script src="{{ asset('/assets/js/sortable.js') }}"></script>

resources/views/admin/partials/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand mb-2">
      <a href="{{ route('adm.panel') }}"><img src="{{ asset('/assets/img/brand.svg') }}" width="50"></a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="{{ route('adm.panel') }}"><img src="{{ asset('/assets/img/brand.svg') }}" width="50"></a>
    </div>
    <ul class="sidebar-menu">
      <li class="menu-header">Módulos</li>
      <li>
        <a href="{{route('adm.home.index')}}">
            <i class="icon icon-home icon-2x"></i>
        <span>Home</span>
      </a>
      </li>
      <li class="dropdown ">
        <a href="#" class="nav-link has-dropdown">
          <i class="icon icon-servicos icon-2x"></i>
          <span>Serviços</span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li>
            <a class="nav-link" href="{{route('adm.service.index')}}" title="Serviços">Serviços</a>
          </li>
          <li>
            <a class="nav-link" href="{{route('adm.service.createDesc')}}" title="Categorias">Descrição</a>
          </li>
          <li>
            <a class="nav-link" href="{{route('adm.service.createNumber')}}" title="Categorias">Números</a>
          </li>
        </ul>
      </li>
      <li class="dropdown ">
        <a href="#" class="nav-link has-dropdown">
          <i class="icon icon-servicos icon-2x"></i>
          <span>Sobre</span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li>
            <a class="nav-link" href="{{route('adm.service.createAbout')}}" title="Sobre">Sobre</a>
          </li>
          <li>
            <a class="nav-link" href="{{route('adm.service.createNumber')}}" title="Categorias">Números</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="{{route('adm.testimonial.index')}}">
            <i class="icon icon-servicos icon-2x "></i>
        <span>Depoimentos</span>
      </a>
      </li>
      <li class="dropdown ">
        <a href="#" class="nav-link has-dropdown">
          <i class="icon icon-servicos icon-2x"></i>
          <span>Profissionais</span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li>
            <a class="nav-link" href="{{route('adm.team.index')}}" title="Serviços">Profissionais</a>
          </li>
          <li>
            <a class="nav-link" href="{{route('adm.team.createDesc')}}" title="Categorias">Descrição</a>
          </li>
        </ul>
      </li>
      <li class="dropdown ">
        <a href="#" class="nav-link has-dropdown">
          <i class="icon icon-noticias lga"></i>
          <span>Postagens</span>
        </a>
        <ul class="dropdown-menu" style="display: none;">
          <li>
            <a class="nav-link" href="{{route('adm.post.index')}}" title="Postagens">Postagens</a>
          </li>
          <li>
            <a class="nav-link" href="{{route('adm.post.category.index')}}" title="Categorias">Categorias</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="{{route('adm.contact')}}">
            <i class="icon icon-contato icon-2x "></i>
        <span>Contatos</span>
      </a>
      </li>
    </ul>
  </aside>
</div>

resources/views/admin/partials/styles.blade.php
<!-- General CSS Files -->
<link rel="stylesheet" href="{{ asset('/assets/modules/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/modules/fontawesome/css/all.min.css') }}">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.css">

<!-- CSS Libraries -->

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('/assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/css/components.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/css/custom.css') }}">
<link rel="stylesheet" href="{{ asset('/assets/js-duallistbox/bootstrap-duallistbox.min.css') }}">
<link rel="stylesheet" href="{{asset('assets_fronts/icon-fonts/css/style.css')}}">