routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('home')->get('/', 'SiteController@index');
//Route::name('home')->get('/site', 'SiteController@index');
/* Route::name('construcao')->get('/construcao', 'SiteController@construcao'); */
Route::name('noticias')->get('/site/noticias', 'SiteController@noticias');
Route::name('artigo')->get('/site/noticias/{slug}', 'SiteController@article');

Auth::routes(['register' => false]);

Route::post('contact', 'SiteController@contact')->name('site.contact');

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');
    Route::get('contatos', 'AdminController@contact')->name('contact');

    Route::prefix('inicio')->name('home.')->group(function() {
        Route::get('', 'HomeController@index')->name('index');
        Route::get('create', 'HomeController@create')->name('create');
        Route::post('create', 'HomeController@store')->name('store');
        Route::get('{id}', 'HomeController@show')->name('show');
        Route::post('{id}', 'HomeController@update')->name('update');
        Route::get('{id}/delete', 'HomeController@delete')->name('delete'); 
    });

    Route::prefix('servicos')->name('service.')->group(function() {
        Route::get('', 'ServiceController@index')->name('index');
        Route::get('create', 'ServiceController@create')->name('create');
        Route::post('create', 'ServiceController@store')->name('store');
        Route::get('descricao', 'ServiceController@createDesc')->name('createDesc');
        Route::post('descricao', 'ServiceController@updateDesc')->name('updateDesc');
        Route::get('sobre', 'ServiceController@createAbout')->name('createAbout');
        Route::post('sobre', 'ServiceController@updateAbout')->name('updateAbout');
        Route::get('numeros', 'ServiceController@createNumber')->name('createNumber');
        Route::post('numeros', 'ServiceController@updateNumber')->name('updateNumber');
        Route::get('{id}', 'ServiceController@show')->name('show');
        Route::post('{id}', 'ServiceController@update')->name('update');
        Route::get('{id}/delete', 'ServiceController@delete')->name('delete'); 
    });

    Route::prefix('depoimento')->name('testimonial.')->group(function() {
        Route::get('', 'TestimonyController@index')->name('index');
        Route::get('create', 'TestimonyController@create')->name('create');
        Route::post('create', 'TestimonyController@store')->name('store');
        Route::get('{id}', 'TestimonyController@show')->name('show');
        Route::post('{id}', 'TestimonyController@update')->name('update');
        Route::get('{id}/delete', 'TestimonyController@delete')->name('delete'); 
    });

    Route::prefix('profissionais')->name('team.')->group(function() {
        Route::get('', 'TeamController@index')->name('index');
        Route::get('create', 'TeamController@create')->name('create');
        Route::post('create', 'TeamController@store')->name('store');
        Route::get('descricao', 'TeamController@createDesc')->name('createDesc');
        Route::post('descricao', 'TeamController@updateDesc')->name('updateDesc');
        Route::get('{id}', 'TeamController@show')->name('show');
        Route::post('{id}', 'TeamController@update')->name('update');
        Route::get('{id}/delete', 'TeamController@delete')->name('delete'); 
    });

    Route::prefix('posts/categorias')->name('post.category.')->group(function() {
        Route::get('', 'PostCategoryController@index')->name('index');
        Route::get('create', 'PostCategoryController@create')->name('create');
        Route::post('create', 'PostCategoryController@store')->name('store');
        Route::get('{id}', 'PostCategoryController@show')->name('show');
        Route::post('{id}', 'PostCategoryController@update')->name('update');
        Route::get('{id}/delete', 'PostCategoryController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('', 'PostController@index')->name('index');
        Route::get('create', 'PostController@create')->name('create');
        Route::post('create', 'PostController@store')->name('store');
        Route::get('{id}', 'PostController@show')->name('show');
        Route::post('{id}', 'PostController@update')->name('update');
        Route::get('{id}/delete', 'PostController@delete')->name('delete');
    });
});

app/Models/Service.php
<?php

namespace App\Models;

use App\Scopes\LangScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Service extends Model
{
    use LangScope;

    protected $fillable = [
        'name', 'short', 'text', 'lang'
    ];
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\About;
use App\Models\Number;
use App\Models\Service;
use App\Models\ServiceDesc;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    protected $service;

    public function __construct(Service $s) {
        $this->middleware('auth');
        $this->service = $s;
    }

    public function index()
    {
        $data = $this->service->all();

        return view('admin.dashboard.service.index', compact('data'));
    }

    public function create()
    {
        return view('admin.dashboard.service.form');
    }

    public function createAbout()
    {
        $pt = About::find(1);
        $en = About::find(2);

        return view('admin.dashboard.service.about', compact('pt', 'en'));
    }

    public function updateAbout(Request $request)
    {
        $input = $request->except(['_token']);

        if (isset($input['img'])) {
            $imageName = time().'.'.$input['img']->extension();  
            $input['img']->move(public_path('storage/about'), $imageName);

            $input['img'] = $imageName;
        } else {
            unset($input['img']);
        }
        
        About::whereLang($input['lang'])->update($input);

        toastr()->success('Salvo');

        return redirect()->route('adm.service.createAbout');
    }

    public function createNumber()
    {
        $pt = Number::find(1);
        $en = Number::find(2);

        return view('admin.dashboard.service.number', compact('pt', 'en'));
    }

    public function updateNumber(Request $request)
    {
        $input = $request->except(['_token']);
        
        Number::whereLang($input['lang'])->update($input);

        toastr()->success('Salvo');

        return redirect()->route('adm.service.createNumber');
    }

    public function createDesc()
    {
        $pt = ServiceDesc::find(1);
        $en = ServiceDesc::find(2);

        return view('admin.dashboard.service.desc', compact('pt', 'en'));
    }

    public function updateDesc(Request $request)
    {
        $desc = ServiceDesc::find(1)->update(['desc' => $request->pt]);
        $desc = ServiceDesc::find(2)->update(['desc' => $request->en]);

        toastr()->success('Salvo');

        return redirect()->route('adm.service.createDesc');
    }

    public function store(Request $request)
    {
        $input = $request->all();
        $this->service->create($input);

        return redirect()->route('adm.service.index');
    }

    public function show($id)
    {
        $service = $this->service->find($id);

        return view('admin.dashboard.service.form', compact('service', 'data'));
    }

    public function update($id, Request $request)
    {
        $input = $request->all();
        $this->service->find($id)->update($input);

        return redirect()->route('adm.service.index');
    }

    public function delete($id)
    {
        $this->service->find($id)->delete();
        
        return redirect()->route('adm.service.index');
    }
}

resources/views/admin/dashboard/service/about.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Sobre</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> PT
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateAbout', 'files' => true]) !!}
              {!! Form::hidden('lang', 'pt') !!}
              {!! Form::label('t', 'Título') !!}
              {!! Form::text('title', $pt->title, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Subtítulo') !!}
              {!! Form::textarea('subtitle', $pt->subtitle, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Descrição') !!}
              {!! Form::textarea('desc', $pt->desc, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Imagem') !!}
              {!! Form::file('img') !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}
            </form>
          </div>
        </div>
      </div>
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> EN
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateAbout', 'files' => true]) !!}
              {!! Form::hidden('lang', 'en') !!}
              {!! Form::label('t', 'Título') !!}
              {!! Form::text('title', $en->title, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Subtítulo') !!}
              {!! Form::textarea('subtitle', $en->subtitle, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Descrição') !!}
              {!! Form::textarea('desc', $en->desc, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Imagem') !!}
              {!! Form::file('img') !!}
              <br>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection

resources/views/admin/dashboard/service/desc.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Descrição</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> Título
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateDesc']) !!}
              PT: {!! Form::textarea('pt', $pt->desc, ['class' => 'form-control', 'required']) !!}
              EN: {!! Form::textarea('en', $en->desc, ['class' => 'form-control', 'required']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection

resources/views/admin/dashboard/service/form.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Serviços</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> Cadastrar
            </h4>
          </div>
          <div class="card-body row">
            @if(isset($service))
                {!! Form::model($service, ['route' => ['adm.service.update', $service->id]]) !!}
            @else
                {!! Form::open(['route' => 'adm.service.store']) !!}
            @endif
              Serviço: {!! Form::text('name', null, ['class' => 'form-control', 'required']) !!}
              <br>
              Resumo: {!! Form::text('short', null, ['class' => 'form-control', 'required']) !!}
              <br>
              Lang: {!! Form::select('lang', ['pt' => 'PT', 'en' => 'EN'], null, ['class' => 'form-control', 'required']) !!}
              <br>
              Descrição: {!! Form::textarea('text', null, ['class' => 'form-control ckeditor', 'required']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

@endsection

@section('scripts')
  <script src="http://vip.ufcode.com.br/ckeditor/ckeditor.js"></script>
@endsection

resources/views/admin/dashboard/service/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header d-flex justify-content-between">
    <h1>Serviços</h1>
    <a href="{{ route('adm.service.create') }}" class="btn btn-success">Cadastrar</a>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <table class="table table-responsive">
            <thead class="thead-light">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Serviço</th>
                <th scope="col">Short</th>
                <th scope="col">Lang</th>
                <th scope="col">Opções</th>
              </tr>
            </thead>
            <tbody>
              @foreach($data as $service)
              <tr>
                <th scope="row">{{$service->id}}</th>
                <td>{{$service->name}}</td>
                <td>{{$service->short}}</td>
                <td>{{$service->lang}}</td>
                <td>
                  <a href="{{ route('adm.service.show', $service->id) }}">Editar</a> | 
                  <a href="{{ route('adm.service.delete', $service->id)}} " onclick="return confirm('Deseja mesmo apagar?')">Apagar</a>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection

resources/views/admin/dashboard/service/number.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Nossos Números</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> PT
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateNumber']) !!}
              {!! Form::hidden('lang', 'pt') !!}
              {!! Form::label('t', 'Seção 1') !!}
              {!! Form::text('t1', $pt->t1, ['class' => 'form-control']) !!}
              {!! Form::number('n1', $pt->n1, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 2') !!}
              {!! Form::text('t2', $pt->t2, ['class' => 'form-control']) !!}
              {!! Form::number('n2', $pt->n2, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 3') !!}
              {!! Form::text('t3', $pt->t3, ['class' => 'form-control']) !!}
              {!! Form::number('n3', $pt->n3, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 4') !!}
              {!! Form::text('t4', $pt->t4, ['class' => 'form-control']) !!}
              {!! Form::number('n4', $pt->n4, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 5') !!}
              {!! Form::text('t5', $pt->t5, ['class' => 'form-control']) !!}
              {!! Form::number('n5', $pt->n5, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 6') !!}
              {!! Form::text('t6', $pt->t6, ['class' => 'form-control']) !!}
              {!! Form::number('n6', $pt->n6, ['class' => 'form-control']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}

            </form>
          </div>
        </div>
      </div>
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> EN
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateNumber']) !!}
              {!! Form::hidden('lang', 'en') !!}
              {!! Form::label('t', 'Seção 1') !!}
              {!! Form::text('t1', $en->t1, ['class' => 'form-control']) !!}
              {!! Form::text('n1', $en->n1, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 2') !!}
              {!! Form::text('t2', $en->t2, ['class' => 'form-control']) !!}
              {!! Form::text('n2', $en->n2, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 3') !!}
              {!! Form::text('t3', $en->t3, ['class' => 'form-control']) !!}
              {!! Form::text('n3', $en->n3, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 4') !!}
              {!! Form::text('t4', $en->t4, ['class' => 'form-control']) !!}
              {!! Form::text('n4', $en->n4, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 5') !!}
              {!! Form::text('t5', $en->t5, ['class' => 'form-control']) !!}
              {!! Form::text('n5', $en->n5, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 6') !!}
              {!! Form::text('t6', $en->t6, ['class' => 'form-control']) !!}
              {!! Form::text('n6', $en->n6, ['class' => 'form-control']) !!}
              <br>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection